#!/usr/bin/env python3
"""Generate version_info.txt for PyInstaller from a single version string.

Run before building so the resource file cannot drift from the package
version:

    python make_version_file.py 0.2.1
    pyinstaller wsl_ctl.spec

With no argument the version is read from pyproject.toml.
"""

from __future__ import annotations

import re
import sys
import tomllib
from datetime import date
from pathlib import Path

# --- edit these ------------------------------------------------------------

COMPANY = "VeryGoodCompanyName"
DESCRIPTION = "WSL Controller"
INTERNAL_NAME = "wsl_ctl"
PRODUCT = "WSL Controller"
OUTPUT = Path("version_info.txt")
PYPROJECT = Path("pyproject.toml")

# ---------------------------------------------------------------------------

TEMPLATE = """\
# Generated by make_version_file.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple_},
    prodvers={tuple_},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', {company!r}),
            StringStruct('FileDescription', {description!r}),
            StringStruct('FileVersion', {version!r}),
            StringStruct('InternalName', {internal!r}),
            StringStruct('LegalCopyright', {copyright!r}),
            StringStruct('OriginalFilename', {filename!r}),
            StringStruct('ProductName', {product!r}),
            StringStruct('ProductVersion', {version!r}),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [0x0409, 0x04B0])]),
  ],
)
"""


def parse_version(version: str) -> tuple[int, int, int, int]:
    """Turn a version string into the 4-integer tuple Windows requires.

    Trailing suffixes such as ``-rc1`` or ``.dev0`` are dropped, since the
    binary resource has no field for them; they survive in the version string.

    Raises:
        ValueError: If no leading numeric component can be found.
    """
    match = re.match(r"\D*(\d+(?:\.\d+)*)", version)
    if not match:
        raise ValueError(f"No numeric component in version {version!r}")

    parts = [int(p) for p in match.group(1).split(".")][:4]
    parts += [0] * (4 - len(parts))

    if any(p > 65535 for p in parts):
        raise ValueError(f"Version components must be 0-65535: {version!r}")
    return tuple(parts)  # type: ignore[return-value]


def version_from_pyproject(path: Path) -> str:
    """Read ``project.version`` from *path*."""
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise SystemExit(f"Cannot read {path}: {exc}") from exc

    try:
        return data["project"]["version"]
    except KeyError as exc:
        raise SystemExit(f"No [project] version in {path}") from exc


def main(argv: list[str]) -> int:
    version = argv[1] if len(argv) > 1 else version_from_pyproject(PYPROJECT)

    try:
        numeric = parse_version(version)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    content = TEMPLATE.format(
        tuple_=numeric,
        company=COMPANY,
        description=DESCRIPTION,
        version=".".join(str(p) for p in numeric),
        internal=INTERNAL_NAME,
        copyright=f"Copyright (c) {date.today().year} {COMPANY}",
        filename=f"{INTERNAL_NAME}.exe",
        product=PRODUCT,
    )

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT} for version {version} -> {numeric}")
    Path("version.iss").write_text(
        f'#define AppVersion "{version}"\n', encoding = "utf-8"
    )
    print(f"Wrote version.iss for {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))